# Generated by Django 2.0.2 on 2018-03-03 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('CName', models.TextField(max_length=50)),
                ('CBudget', models.IntegerField()),
                ('CStart', models.DateField()),
                ('CEnd', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EID', models.AutoField(primary_key=True, serialize=False)),
                ('EFName', models.TextField(max_length=50)),
                ('ELName', models.TextField(max_length=50)),
                ('EEmail', models.EmailField(max_length=200)),
                ('isAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('OID', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('orderDate', models.DateField()),
                ('isApproved', models.BooleanField()),
                ('hasArrived', models.BooleanField()),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contract')),
                ('EID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('PName', models.TextField(max_length=50)),
                ('PDescription', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('QID', models.AutoField(primary_key=True, serialize=False)),
                ('QLink', models.TextField(max_length=2000)),
                ('Qprice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False)),
                ('SName', models.TextField(max_length=50)),
                ('SLink', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='SID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Supplier'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='QID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Quote'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='SID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Supplier'),
        ),
    ]
